config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/coordinate-portal:
      branch: main
      repo: https://github.com/cessda/coordinate-portal
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/coordinate-portal git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-apricot-warthog.sh
        container: qc.acc_gimpy-cyan-manatee
  QC.Doc:
    repos:
      github.com/cessda/coordinate-portal find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-olivine-stoat.sh
        container: qc.doc_smelly-gamboge-indri
      github.com/cessda/coordinate-portal git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-pumpkin-olm.sh
        container: qc.doc_geeky-burgundy-wombat
      github.com/cessda/coordinate-portal markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-denim-barb.sh
        container: qc.doc_bluesy-cornflower-chicken
  QC.Lic:
    repos:
      github.com/cessda/coordinate-portal licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-rust-gorilla.sh
        container: qc.lic_stinky-brass-dalmatian
  QC.Met:
    repos:
      github.com/cessda/coordinate-portal cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-cinnamon-collie.sh
        container: qc.met_cheeky-chartreuse-tortoise
  QC.Sty:
    repos:
      github.com/cessda/coordinate-portal hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-wheat-worm.sh
        container: qc.sty_zippy-cardinal-beetle
      github.com/cessda/coordinate-portal jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-yellow-crane.sh
        container: qc.sty_frumpy-vermilion-schnauzer
  QC.Ver:
    repos:
      github.com/cessda/coordinate-portal get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-carmine-jackal.sh
        container: qc.ver_sleepy-buff-spaniel
timeout: 5400
